// src/components/AppHeader.tsx
import { RefreshCw, Sparkles } from "lucide-react";

type AppHeaderProps = {
  showReset?: boolean;
  onReset?: () => void;
};

export function AppHeader({ showReset, onReset }: AppHeaderProps) {
  return (
    <header className="fixed left-0 right-0 top-0 z-40 border-b border-border bg-background/80 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6">
        <div className="flex items-center gap-3">
          <div
            aria-hidden="true"
            className="flex h-9 w-9 items-center justify-center rounded-md bg-primary/15 text-accent"
          >
            <Sparkles className="h-5 w-5" />
          </div>
          <div className="flex flex-col">
            <span className="font-serif text-lg font-medium leading-none tracking-tight text-foreground">
              TopProperties
            </span>
            <span className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground">
              Mallorca Private Office
            </span>
          </div>
        </div>
        {showReset && onReset && (
          <button
            type="button"
            onClick={onReset}
            className="flex min-h-11 items-center gap-2 rounded-full border border-border bg-card px-4 py-2 text-xs font-medium text-muted-foreground transition hover:text-foreground"
          >
            <RefreshCw aria-hidden="true" className="h-3.5 w-3.5" />
            New brief
          </button>
        )}
      </div>
    </header>
  );
}

// components/AppHeader.vue
<template>
  <header class="sticky top-0 z-50 bg-surface-elevated/80 backdrop-blur-md border-b border-stone-200/60">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16 sm:h-20">
        <!-- Logo / Brand -->
        <NuxtLink to="/" class="flex items-center gap-2.5 group">
          <div class="w-8 h-8 rounded-lg bg-stone-950 flex items-center justify-center">
            <span class="text-gold-400 font-display text-sm font-bold">T</span>
          </div>
          <div class="hidden sm:block">
            <span class="font-display text-lg text-stone-950 tracking-tight">TopProperties</span>
            <span class="text-xs text-stone-400 block -mt-0.5 tracking-widest uppercase">Mallorca</span>
          </div>
        </NuxtLink>

        <!-- Nav (placeholder) -->
        <nav class="hidden md:flex items-center gap-8">
          <span class="text-sm text-stone-500 hover:text-stone-900 cursor-default transition-colors">Buy</span>
          <span class="text-sm text-stone-500 hover:text-stone-900 cursor-default transition-colors">Explore</span>
          <span class="text-sm text-stone-500 hover:text-stone-900 cursor-default transition-colors">Insights</span>
        </nav>

        <!-- CTA -->
        <button
          class="bg-stone-950 text-stone-50 text-sm font-medium px-5 py-2.5 rounded-lg hover:bg-stone-800 transition-colors cursor-pointer"
        >
          Start Search
        </button>
      </div>
    </div>
  </header>
</template>
