// src/App.tsx
import type { KeyboardEvent } from "react";
import { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  ArrowRight,
  Bath,
  Bed,
  Building,
  Compass,
  MessageSquare,
  RefreshCw,
  Send,
  Sparkles,
  Square,
  TrendingUp,
  Waves,
} from "lucide-react";
import { cn } from "@/utils/cn";
import {
  DEFAULT_PROMPT,
  SUGGESTIONS,
  type Brief,
  type FollowUp,
  buildBrief,
  buildFollowUpResponse,
} from "@/app-data";

// ------------------------------------------------------------------
// Components
// ------------------------------------------------------------------

const TRADEOFF_ICONS = {
  building: Building,
  compass: Compass,
  "trending-up": TrendingUp,
  waves: Waves,
};

export default function App() {
  const [prompt, setPrompt] = useState(DEFAULT_PROMPT);
  const [submitted, setSubmitted] = useState(false);
  const [brief, setBrief] = useState<Brief | null>(null);
  const [followUps, setFollowUps] = useState<FollowUp[]>([]);
  const [isHoveringSubmit, setIsHoveringSubmit] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, 160)}px`;
  }, [prompt]);

  const handleSubmit = () => {
    const trimmed = prompt.trim();
    if (!trimmed) return;

    if (!submitted) {
      setBrief(buildBrief());
      setSubmitted(true);
      setFollowUps([]);
    } else {
      const answer = buildFollowUpResponse(trimmed);
      setFollowUps((prev) => [...prev, { question: trimmed, answer }]);
    }

    // Keep the composer editable for follow-ups
    setTimeout(() => {
      textareaRef.current?.focus();
    }, 100);
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
      e.preventDefault();
      handleSubmit();
    }
  };

  const applyNextQuestion = () => {
    if (!brief) return;
    setPrompt(brief.nextQuestion);
    setTimeout(() => textareaRef.current?.focus(), 50);
  };

  const resetWorkspace = () => {
    setSubmitted(false);
    setBrief(null);
    setFollowUps([]);
    setPrompt(DEFAULT_PROMPT);
    setTimeout(() => textareaRef.current?.focus(), 50);
  };

  return (
    <div className="relative min-h-screen overflow-x-hidden bg-luxury">
      {/* Background ambient glow */}
      <div className="pointer-events-none fixed inset-0 -z-10">
        <div className="absolute left-1/2 top-0 h-[600px] w-[600px] -translate-x-1/2 rounded-full bg-indigo-600/10 blur-[120px]" />
        <div className="absolute bottom-0 right-0 h-[500px] w-[500px] rounded-full bg-teal-600/8 blur-[120px]" />
      </div>

      {/* Header */}
      <header className="fixed left-0 right-0 top-0 z-40 border-b border-white/5 bg-slate-950/60 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-[0.625rem] bg-indigo-500/10 text-indigo-300">
              <Sparkles className="h-5 w-5" />
            </div>
            <div className="flex flex-col">
              <span className="font-serif text-lg font-medium leading-none tracking-tight text-white">
                TopProperties
              </span>
              <span className="text-[10px] uppercase tracking-[0.2em] text-slate-500">
                Mallorca Private Office
              </span>
            </div>
          </div>
          {submitted && (
            <button
              onClick={resetWorkspace}
              className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-medium text-slate-300 transition hover:bg-white/10 hover:text-white"
            >
              <RefreshCw className="h-3.5 w-3.5" />
              New brief
            </button>
          )}
        </div>
      </header>

      {/* Main workspace */}
      <main className="relative z-10">
        <AnimatePresence mode="wait">
          {!submitted ? (
            <motion.div
              key="workspace"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.5 }}
              className="flex min-h-screen flex-col items-center justify-center px-6 pb-80 pt-32 text-center sm:pb-56"
            >
              <div className="mx-auto max-w-3xl">
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: 0.1 }}
                  className="mb-8 inline-flex items-center gap-2 rounded-full border border-indigo-400/20 bg-indigo-500/10 px-4 py-1.5 text-xs font-semibold uppercase tracking-[0.15em] text-indigo-300"
                >
                  <Sparkles className="h-3.5 w-3.5" />
                  Agentic briefing
                </motion.div>

                <motion.h1
                  initial={{ opacity: 0, y: 24 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.7, delay: 0.2 }}
                  className="font-serif text-5xl font-medium leading-[1.05] tracking-tight text-white md:text-7xl"
                >
                  Find your place
                  <br />
                  <span className="text-slate-400">in Mallorca</span>
                </motion.h1>

                <motion.p
                  initial={{ opacity: 0, y: 24 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.7, delay: 0.3 }}
                  className="mx-auto mt-6 max-w-xl text-lg leading-relaxed text-slate-400"
                >
                  Describe what home means to you. We’ll generate a curated brief of properties,
                  tradeoffs, and the one question that will move your search forward.
                </motion.p>

                <motion.div
                  initial={{ opacity: 0, y: 24 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.7, delay: 0.4 }}
                  className="mt-10 flex flex-wrap justify-center gap-3"
                >
                  {SUGGESTIONS.map((suggestion) => (
                    <button
                      key={suggestion}
                      onClick={() => setPrompt(suggestion)}
                      className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-slate-300 transition hover:border-indigo-400/30 hover:bg-white/10 hover:text-white"
                    >
                      {suggestion}
                    </button>
                  ))}
                </motion.div>
              </div>
            </motion.div>
          ) : (
            <motion.div
              key="brief"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
              className="mx-auto max-w-6xl px-6 pb-96 pt-36 sm:pb-72"
            >
              {/* Brief header */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
                className="mb-10"
              >
                <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.15em] text-indigo-300">
                  <Sparkles className="h-3.5 w-3.5" />
                  Generated property brief
                </div>
                <h2 className="mt-3 font-serif text-4xl font-medium tracking-tight text-white md:text-5xl">
                  Your Mallorca brief
                </h2>
                <p className="mt-3 max-w-2xl text-slate-400">
                  Curated for “{prompt}”. Three directions, one tradeoff panel, and the next best
                  question to answer.
                </p>
              </motion.div>

              {/* Brief summary */}
              <motion.section
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.1 }}
                className="mb-12 rounded-[8px] border border-white/10 bg-white/[0.04] p-8 backdrop-blur-sm md:p-10"
              >
                <h3 className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">
                  Brief summary
                </h3>
                <p className="mt-4 font-serif text-xl leading-relaxed text-slate-100 md:text-2xl">
                  {brief?.summary}
                </p>
              </motion.section>

              {/* Property recommendations */}
              <section className="mb-16">
                <div className="mb-6 flex items-center justify-between">
                  <h3 className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">
                    Curated recommendations
                  </h3>
                  <span className="text-xs text-slate-500">3 properties</span>
                </div>
                <div className="grid gap-6 md:grid-cols-3">
                  {brief?.properties.map((property, index) => (
                    <motion.article
                      key={property.id}
                      initial={{ opacity: 0, y: 30 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.6, delay: 0.2 + index * 0.1 }}
                      className="group relative flex flex-col overflow-hidden rounded-[8px] border border-white/10 bg-white/[0.04] transition hover:border-white/20"
                    >
                      <div className="relative aspect-[4/3] overflow-hidden">
                        <img
                          src={property.image}
                          alt={property.name}
                          className="h-full w-full object-cover transition duration-700 group-hover:scale-105"
                        />
                        <div className="absolute inset-0 bg-gradient-to-t from-slate-950/60 to-transparent" />
                        <div className="absolute bottom-4 left-4 rounded-full bg-slate-950/60 px-3 py-1 text-xs font-medium text-white backdrop-blur-md">
                          {property.location}
                        </div>
                      </div>
                      <div className="flex flex-1 flex-col p-6">
                        <div className="flex items-start justify-between gap-4">
                          <div>
                            <h4 className="font-serif text-2xl text-white">{property.name}</h4>
                            <p className="mt-1 text-sm text-slate-400">{property.location}</p>
                          </div>
                          <span className="whitespace-nowrap text-lg font-medium text-white">
                            {property.price}
                          </span>
                        </div>
                        <p className="mt-4 flex-1 text-sm leading-relaxed text-slate-300">
                          {property.why}
                        </p>
                        <div className="mt-6 flex items-center gap-4 text-xs text-slate-400">
                          <span className="flex items-center gap-1.5">
                            <Bed className="h-4 w-4" />
                            {property.beds} beds
                          </span>
                          <span className="flex items-center gap-1.5">
                            <Bath className="h-4 w-4" />
                            {property.baths} baths
                          </span>
                          <span className="flex items-center gap-1.5">
                            <Square className="h-4 w-4" />
                            {property.sqm} m²
                          </span>
                        </div>
                        <div className="mt-5 flex flex-wrap gap-2">
                          {property.tags.map((tag) => (
                            <span
                              key={tag}
                              className="rounded-full border border-white/10 bg-white/5 px-2.5 py-1 text-[11px] text-slate-300"
                            >
                              {tag}
                            </span>
                          ))}
                        </div>
                      </div>
                    </motion.article>
                  ))}
                </div>
              </section>

              {/* Buyer tradeoff panel */}
              <section className="mb-16">
                <div className="mb-6">
                  <h3 className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">
                    Editorial tradeoff panel
                  </h3>
                  <p className="mt-2 max-w-2xl text-sm text-slate-400">
                    Comparing the four buying dimensions that matter most in Mallorca: privacy, sea
                    access, Palma convenience, and investment confidence.
                  </p>
                </div>
                <div className="grid gap-4 md:grid-cols-2">
                  {brief?.tradeoffs.map((tradeoff, index) => (
                    <TradeoffCard key={tradeoff.label} tradeoff={tradeoff} index={index} />
                  ))}
                </div>
              </section>

              {/* Next best question */}
              <motion.section
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.7 }}
                className="relative overflow-hidden rounded-[8px] border border-indigo-400/20 bg-indigo-950/30 p-8 text-center backdrop-blur-md md:p-12"
              >
                <div className="absolute -left-16 -top-16 h-40 w-40 rounded-full bg-indigo-500/20 blur-[80px]" />
                <div className="absolute -bottom-16 -right-16 h-40 w-40 rounded-full bg-teal-500/10 blur-[80px]" />
                <div className="relative">
                  <div className="mx-auto mb-5 flex h-12 w-12 items-center justify-center rounded-full bg-indigo-500/15 text-indigo-300">
                    <MessageSquare className="h-5 w-5" />
                  </div>
                  <h3 className="font-serif text-2xl text-white md:text-3xl">Next best question</h3>
                  <p className="mx-auto mt-4 max-w-2xl text-lg leading-relaxed text-indigo-100">
                    {brief?.nextQuestion}
                  </p>
                  <button
                    onClick={applyNextQuestion}
                    className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-medium text-indigo-950 transition hover:bg-indigo-50"
                  >
                    Answer this question
                    <ArrowRight className="h-4 w-4" />
                  </button>
                </div>
              </motion.section>

              {/* Follow-up responses */}
              {followUps.length > 0 && (
                <section className="mt-16">
                  <h3 className="mb-6 text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">
                    Follow-up notes
                  </h3>
                  <div className="space-y-4">
                    {followUps.map((followUp, index) => (
                      <motion.div
                        key={index}
                        initial={{ opacity: 0, y: 16 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.4 }}
                        className="rounded-[8px] border border-white/10 bg-white/[0.04] p-6"
                      >
                        <p className="text-xs text-slate-500">You asked: “{followUp.question}”</p>
                        <p className="mt-2 text-slate-200">{followUp.answer}</p>
                      </motion.div>
                    ))}
                  </div>
                </section>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      {/* Persistent Brief Composer */}
      <motion.div
        layout
        className="fixed bottom-3 left-1/2 z-50 w-[calc(100%-1rem)] max-w-3xl -translate-x-1/2 pb-[env(safe-area-inset-bottom)] sm:bottom-6 sm:w-[calc(100%-2rem)] md:bottom-8"
      >
        <div className="rounded-[8px] border border-white/10 bg-slate-900/85 shadow-2xl shadow-black/50 backdrop-blur-2xl">
          <div className="flex items-end gap-2 p-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[0.625rem] bg-indigo-500/10 text-indigo-300">
              <Sparkles className="h-5 w-5" />
            </div>
            <textarea
              ref={textareaRef}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              onKeyDown={handleKeyDown}
              rows={1}
              placeholder="Describe the home you are looking for..."
              className="max-h-40 min-h-[44px] flex-1 resize-none bg-transparent px-2 py-2.5 text-base leading-relaxed text-white placeholder:text-slate-500 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950"
            />
            <button
              onClick={handleSubmit}
              onMouseEnter={() => setIsHoveringSubmit(true)}
              onMouseLeave={() => setIsHoveringSubmit(false)}
              disabled={!prompt.trim()}
              className={cn(
                "flex h-11 w-11 shrink-0 items-center justify-center rounded-[0.625rem] text-sm font-medium transition sm:w-auto sm:px-4",
                prompt.trim()
                  ? "bg-white text-slate-950 hover:bg-indigo-50"
                  : "cursor-not-allowed bg-white/10 text-slate-500",
              )}
            >
              <span className="flex items-center gap-2">
                <span className="sr-only sm:not-sr-only">
                  {submitted ? "Send" : "Generate brief"}
                </span>
                {isHoveringSubmit || !submitted ? (
                  submitted ? <Send className="h-4 w-4" /> : <ArrowRight className="h-4 w-4" />
                ) : (
                  <Send className="h-4 w-4" />
                )}
              </span>
            </button>
          </div>
          <div className="flex items-center justify-between gap-3 border-t border-white/5 px-4 py-2.5">
            <span className="text-[11px] font-medium uppercase tracking-[0.15em] text-slate-500">
              Persistent Brief Composer
            </span>
            <span className="text-right text-[11px] text-slate-600">
              {submitted ? "Edit or ask a follow-up" : "Press ⌘ + Enter to submit"}
            </span>
          </div>
        </div>
      </motion.div>
    </div>
  );
}

function TradeoffCard({
  tradeoff,
  index,
}: {
  tradeoff: NonNullable<Brief["tradeoffs"]>[number];
  index: number;
}) {
  const Icon = TRADEOFF_ICONS[tradeoff.icon];

  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.4 + index * 0.08 }}
      className="rounded-[8px] border border-white/10 bg-white/[0.04] p-6 backdrop-blur-sm transition hover:border-white/20"
    >
      <div className="flex items-center gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-full bg-indigo-500/10 text-indigo-300">
          <Icon className="h-5 w-5" />
        </div>
        <span className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">
          {tradeoff.label}
        </span>
      </div>
      <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <span className="font-serif text-xl text-white">{tradeoff.winner}</span>
        <span className="rounded-full border border-indigo-300/15 bg-indigo-400/10 px-3 py-1 text-xs font-medium uppercase tracking-[0.12em] text-indigo-200">
          {tradeoff.verdict}
        </span>
      </div>
      <p className="mt-3 text-sm leading-relaxed text-slate-300">{tradeoff.note}</p>
    </motion.div>
  );
}

// src/App.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { ArrowUpRight, Bot, Check, Compass, MapPinned, MessageCircle, Sparkles } from "@lucide/vue";
import { composePrototypeBrief, defaultPrompt } from "./data/prototype";

const prompt = ref(defaultPrompt);
const submittedPrompt = ref(defaultPrompt);

const brief = computed(() => composePrototypeBrief(submittedPrompt.value));
const leadHome = computed(() => brief.value.matches[0]);
const supportingHomes = computed(() => brief.value.matches.slice(1));

function composeBrief() {
  submittedPrompt.value = prompt.value;
}
</script>

<template>
  <main class="min-h-screen overflow-x-hidden bg-[#ece7dc] text-[#18221d]">
    <section class="relative isolate min-h-screen px-4 py-4 sm:px-6 lg:px-8">
      <div
        aria-hidden="true"
        class="absolute inset-0 -z-20 bg-[radial-gradient(circle_at_18%_18%,#ffffff_0,transparent_30%),radial-gradient(circle_at_86%_12%,#bfdcd5_0,transparent_34%),linear-gradient(135deg,#f8f4ea_0%,#e6dfd1_100%)]"
      />
      <div aria-hidden="true" class="absolute inset-0 -z-10 opacity-45 blueprint-grid" />

      <div
        class="mx-auto grid min-h-[calc(100vh-2rem)] w-full max-w-[1480px] gap-4 lg:grid-cols-[86px_minmax(0,1fr)_380px]"
      >
        <aside
          class="hidden rounded-[28px] border border-white/70 bg-white/55 p-4 shadow-[0_24px_70px_rgba(47,54,45,0.12)] backdrop-blur-xl lg:flex lg:flex-col lg:items-center lg:justify-between"
          aria-label="Prototype navigation"
        >
          <a
            href="#topproperties-prototype"
            class="focus-ring grid size-12 place-items-center rounded-2xl bg-[#17241f] text-sm font-black text-[#f8f4ea]"
          >
            TP
          </a>
          <nav class="grid gap-3" aria-label="Prototype sections">
            <a class="nav-dot is-active" href="#topproperties-prototype" aria-label="Brief" />
            <a class="nav-dot" href="#property-options" aria-label="Properties" />
            <a class="nav-dot" href="#area-intelligence" aria-label="Areas" />
          </nav>
          <span class="vertical-label">Mallorca</span>
        </aside>

        <section id="topproperties-prototype" class="grid gap-4">
          <header
            class="flex items-center justify-between gap-4 rounded-[28px] border border-white/70 bg-white/60 px-4 py-3 shadow-[0_18px_54px_rgba(47,54,45,0.1)] backdrop-blur-xl sm:px-5"
          >
            <div>
              <p class="text-xs font-black uppercase tracking-[0.18em] text-[#657269]">
                TopProperties
              </p>
              <p class="text-sm font-semibold text-[#26352e]">Luxury discovery assistant</p>
            </div>
            <div class="hidden items-center gap-2 md:flex">
              <span class="status-pill">Mallorca only</span>
              <span class="status-pill">Mock AI</span>
            </div>
            <button
              class="focus-ring inline-flex size-11 items-center justify-center rounded-2xl bg-[#dba94f] text-[#17241f] shadow-[0_14px_28px_rgba(219,169,79,0.28)]"
              type="button"
              aria-label="Open generated brief"
            >
              <Sparkles :size="18" aria-hidden="true" />
            </button>
          </header>

          <div class="grid gap-4 xl:grid-cols-[minmax(0,1.15fr)_minmax(360px,0.85fr)]">
            <article
              class="relative min-h-[620px] overflow-hidden rounded-[34px] border border-white/75 bg-[#17241f] shadow-[0_34px_90px_rgba(38,53,46,0.2)]"
              aria-labelledby="hero-title"
            >
              <img
                :src="leadHome.image"
                :alt="`${leadHome.name} luxury home visual reference`"
                class="absolute inset-0 h-full w-full object-cover opacity-80"
              />
              <div
                aria-hidden="true"
                class="absolute inset-0 bg-[linear-gradient(90deg,rgba(15,24,20,0.86),rgba(15,24,20,0.22)_58%,rgba(15,24,20,0.5)),linear-gradient(0deg,rgba(15,24,20,0.66),transparent_48%)]"
              />

              <div class="relative z-10 flex min-h-[620px] flex-col justify-between p-5 sm:p-7">
                <div class="max-w-[620px] space-y-5">
                  <div
                    class="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/12 px-3 py-2 text-xs font-black uppercase tracking-[0.16em] text-[#d8f0ea] backdrop-blur-md"
                  >
                    <Bot :size="15" aria-hidden="true" />
                    Agent-composed brief
                  </div>
                  <h1
                    id="hero-title"
                    class="max-w-[10ch] text-[3.4rem] font-black leading-[0.9] tracking-normal text-white sm:text-[5rem] lg:text-[6.4rem]"
                  >
                    Find the right Mallorca home.
                  </h1>
                  <p class="max-w-[34rem] text-base leading-7 text-[#f5efe4] sm:text-lg">
                    A Figma-inspired showcase for luxury buyers comparing lifestyle, privacy, and
                    investment confidence before a move or second home.
                  </p>
                </div>

                <form
                  class="grid gap-3 rounded-[24px] border border-white/24 bg-white/18 p-3 shadow-[0_26px_70px_rgba(0,0,0,0.22)] backdrop-blur-xl sm:grid-cols-[1fr_auto]"
                  @submit.prevent="composeBrief"
                >
                  <label class="sr-only" for="buyer-prompt">Buyer prompt</label>
                  <input
                    id="buyer-prompt"
                    v-model="prompt"
                    class="min-h-14 min-w-0 rounded-[18px] border border-white/70 bg-[#fffaf0] px-4 text-[0.98rem] font-semibold text-[#17241f] outline-none placeholder:text-[#6d766e] focus:border-[#dba94f]"
                    autocomplete="off"
                  />
                  <button
                    class="focus-ring inline-flex min-h-14 items-center justify-center gap-2 rounded-[18px] bg-[#dba94f] px-5 text-sm font-black text-[#17241f] transition hover:bg-[#efbf66]"
                    type="submit"
                    aria-label="Compose Mallorca property brief"
                  >
                    Generate
                    <ArrowUpRight :size="18" aria-hidden="true" />
                  </button>
                </form>
              </div>
            </article>

            <div class="grid gap-4">
              <article class="figma-panel p-5 sm:p-6">
                <div class="mb-5 flex items-start justify-between gap-4">
                  <div>
                    <p class="eyebrow">AI response</p>
                    <h2 class="mt-2 text-2xl font-black leading-tight sm:text-3xl">
                      {{ brief.intent }}
                    </h2>
                  </div>
                  <span
                    class="grid size-12 place-items-center rounded-2xl bg-[#17241f] text-[#d8f0ea]"
                  >
                    <MessageCircle :size="20" aria-hidden="true" />
                  </span>
                </div>
                <div class="rounded-[24px] bg-[#f6f1e6] p-4">
                  <p class="text-sm font-black uppercase tracking-[0.14em] text-[#6a746d]">
                    Prompt
                  </p>
                  <p class="mt-2 text-xl font-black leading-tight">"{{ brief.prompt }}"</p>
                </div>
                <p class="mt-5 text-base leading-7 text-[#4d5a52]">{{ brief.summary }}</p>
              </article>

              <article id="area-intelligence" class="figma-panel min-h-[320px] overflow-hidden p-5">
                <div class="mb-4 flex items-center justify-between">
                  <div>
                    <p class="eyebrow">Map intelligence</p>
                    <h2 class="mt-1 text-xl font-black">Lifestyle zones</h2>
                  </div>
                  <MapPinned :size="22" aria-hidden="true" class="text-[#416b5e]" />
                </div>
                <div class="relative h-[230px] overflow-hidden rounded-[28px] bg-[#dce9e4]">
                  <div class="absolute inset-5 rounded-full border border-[#17241f]/15" />
                  <div class="map-blob left-[16%] top-[47%] bg-[#6d9081]" />
                  <div class="map-blob right-[22%] top-[18%] bg-[#dba94f]" />
                  <div class="map-blob bottom-[16%] right-[14%] bg-[#90bbb2]" />
                  <div class="absolute bottom-3 left-3 right-3 grid grid-cols-3 gap-2">
                    <div v-for="area in brief.areas" :key="area.area" class="map-label">
                      <span>{{ area.tone }}</span>
                      <strong>{{ area.area }}</strong>
                    </div>
                  </div>
                </div>
              </article>
            </div>
          </div>

          <section id="property-options" class="grid gap-4 xl:grid-cols-[1fr_1fr]">
            <article
              v-for="home in supportingHomes"
              :key="home.id"
              class="figma-panel grid overflow-hidden p-0 sm:grid-cols-[190px_1fr]"
            >
              <img
                :src="home.image"
                :alt="`${home.name} luxury home visual reference`"
                class="h-56 w-full object-cover sm:h-full"
              />
              <div class="space-y-4 p-5">
                <div>
                  <p class="eyebrow">{{ home.area }} / {{ home.price }}</p>
                  <h3 class="mt-2 text-2xl font-black leading-tight">{{ home.name }}</h3>
                </div>
                <p class="text-sm font-black text-[#2f5548]">{{ home.fit }}</p>
                <p class="text-sm leading-6 text-[#5b675f]">{{ home.thesis }}</p>
                <ul class="flex flex-wrap gap-2">
                  <li v-for="highlight in home.highlights" :key="highlight" class="soft-pill">
                    {{ highlight }}
                  </li>
                </ul>
              </div>
            </article>
          </section>
        </section>

        <aside class="grid gap-4 lg:grid-rows-[auto_1fr]" aria-label="Generated brief details">
          <section class="figma-panel p-5">
            <p class="eyebrow">Recommended first</p>
            <h2 class="mt-2 text-2xl font-black leading-tight">{{ leadHome.name }}</h2>
            <p class="mt-3 text-sm font-black text-[#2f5548]">{{ leadHome.fit }}</p>
            <p class="mt-4 text-sm leading-6 text-[#5b675f]">{{ leadHome.thesis }}</p>
            <dl class="mt-5 grid grid-cols-3 gap-2">
              <div class="metric">
                <dt>Privacy</dt>
                <dd>{{ leadHome.signals.privacy }}</dd>
              </div>
              <div class="metric">
                <dt>Airport</dt>
                <dd>{{ leadHome.signals.airport }}</dd>
              </div>
              <div class="metric">
                <dt>Mode</dt>
                <dd>{{ leadHome.signals.lifestyle }}</dd>
              </div>
            </dl>
          </section>

          <section class="figma-panel flex flex-col p-5">
            <div class="mb-5 flex items-center justify-between">
              <div>
                <p class="eyebrow">Tradeoff stack</p>
                <h2 class="mt-1 text-xl font-black">How to choose</h2>
              </div>
              <Compass :size="22" aria-hidden="true" class="text-[#416b5e]" />
            </div>
            <div class="grid gap-3">
              <article v-for="area in brief.areas" :key="area.area" class="choice-row">
                <Check :size="17" aria-hidden="true" class="mt-1 shrink-0 text-[#dba94f]" />
                <div>
                  <h3 class="font-black">{{ area.area }}</h3>
                  <p class="mt-1 text-sm leading-6 text-[#5b675f]">
                    {{ area.mood }}. {{ area.buyerFit }}; {{ area.timing }}.
                  </p>
                </div>
              </article>
            </div>
          </section>
        </aside>
      </div>
    </section>
  </main>
</template>
